# Use a imagem oficial do Node.js 20
FROM node:20

# Defina o diretório de trabalho no container
WORKDIR /app

# Copie o arquivo package.json e package-lock.json (se existir)
COPY package*.json ./

# Instale as dependências do projeto
RUN npm install

# Copie todo o código do projeto para o diretório de trabalho no container
COPY . .

# Exponha a porta que o seu aplicativo vai rodar (por exemplo, 3000)
EXPOSE 5173

# Execute o comando de desenvolvimento usando o script `dev` do package.json
CMD ["npm", "run", "dev"]